// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file RobotState.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "motoman_hardware/RobotState.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

motoman_description::msg::RobotState::RobotState()
{
    // m_state com.eprosima.idl.parser.typecode.PrimitiveTypeCode@e056f20
    m_state = 0;
    // m_code com.eprosima.idl.parser.typecode.PrimitiveTypeCode@10e41621
    m_code = 0;

}

motoman_description::msg::RobotState::~RobotState()
{

}

motoman_description::msg::RobotState::RobotState(
        const RobotState& x)
{
    m_state = x.m_state;
    m_code = x.m_code;
}

motoman_description::msg::RobotState::RobotState(
        RobotState&& x)
{
    m_state = x.m_state;
    m_code = x.m_code;
}

motoman_description::msg::RobotState& motoman_description::msg::RobotState::operator =(
        const RobotState& x)
{

    m_state = x.m_state;
    m_code = x.m_code;

    return *this;
}

motoman_description::msg::RobotState& motoman_description::msg::RobotState::operator =(
        RobotState&& x)
{

    m_state = x.m_state;
    m_code = x.m_code;

    return *this;
}

bool motoman_description::msg::RobotState::operator ==(
        const RobotState& x) const
{

    return (m_state == x.m_state && m_code == x.m_code);
}

bool motoman_description::msg::RobotState::operator !=(
        const RobotState& x) const
{
    return !(*this == x);
}

size_t motoman_description::msg::RobotState::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

size_t motoman_description::msg::RobotState::getCdrSerializedSize(
        const motoman_description::msg::RobotState& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

void motoman_description::msg::RobotState::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_state;
    scdr << m_code;

}

void motoman_description::msg::RobotState::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_state;
    dcdr >> m_code;
}

/*!
 * @brief This function sets a value in member state
 * @param _state New value for member state
 */
void motoman_description::msg::RobotState::state(
        int8_t _state)
{
    m_state = _state;
}

/*!
 * @brief This function returns the value of member state
 * @return Value of member state
 */
int8_t motoman_description::msg::RobotState::state() const
{
    return m_state;
}

/*!
 * @brief This function returns a reference to member state
 * @return Reference to member state
 */
int8_t& motoman_description::msg::RobotState::state()
{
    return m_state;
}

/*!
 * @brief This function sets a value in member code
 * @param _code New value for member code
 */
void motoman_description::msg::RobotState::code(
        int8_t _code)
{
    m_code = _code;
}

/*!
 * @brief This function returns the value of member code
 * @return Value of member code
 */
int8_t motoman_description::msg::RobotState::code() const
{
    return m_code;
}

/*!
 * @brief This function returns a reference to member code
 * @return Reference to member code
 */
int8_t& motoman_description::msg::RobotState::code()
{
    return m_code;
}


size_t motoman_description::msg::RobotState::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;



    return current_align;
}

bool motoman_description::msg::RobotState::isKeyDefined()
{
    return false;
}

void motoman_description::msg::RobotState::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}


