controller_manager:
  ros__parameters:
    update_rate: 250 # Hz

    # new
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # # old
    # joint_state_controller:
    #   type: joint_state_controller/JointStateController

    JointGroupPositionController:
    #forward_command_controller_position:
      type: position_controllers/JointGroupPositionController
      #type: forward_command_controller/ForwardCommandController

    StaticTestController:
      type: motoman_controllers/StaticTest

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController



JointGroupPositionController:
  ros__parameters:
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
    interface_name: position

StaticTestController:
  ros__parameters:
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
    interface_name: position

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03
