controller_manager:
  ros__parameters:
    update_rate: 250 # Hz

    # new
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # # old
    # joint_state_controller:
    #   type: joint_state_controller/JointStateController

    JointGroupPositionController:
    #forward_command_controller_position:
      type: position_controllers/JointGroupPositionController
      #type: forward_command_controller/ForwardCommandController

    StaticTestController:
      type: motoman_controllers/StaticTest

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle


JointGroupPositionController:
  ros__parameters:
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
    interface_name: position

StaticTestController:
  ros__parameters:
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
    interface_name: position
    state_interfaces:
      # - position
      - pos_fdb

joint_trajectory_controller:
  ros__parameters:
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03

cartesian_motion_controller:
  ros__parameters:
    end_effector_link: "tool_marker"
    robot_base_link: "base_link"
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
    command_interfaces:
      - position
    solver:
        error_scale: 1.0
        iterations: 20
    pd_gains:
        trans_x: {p: 1.0}
        trans_y: {p: 1.0}
        trans_z: {p: 1.0}
        rot_x: {p: 0.5}
        rot_y: {p: 0.5}
        rot_z: {p: 0.5}

motion_control_handle:
  ros__parameters:
    end_effector_link: "tool_marker"
    robot_base_link: "base_link"
    ft_sensor_ref_link: "tool_marker"
    joints:
      - joint_1_s
      - joint_2_l
      - joint_3_u
      - joint_4_r
      - joint_5_b
      - joint_6_t
